version: '3.1'
services:
  app:
    container_name: springboot-postgresql
    image: recycle-docker
    build: ./
    ports:
      - "9091:9091"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: mdillon/postgis:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=RecycleMap